# Generated by Django 4.0.4 on 2022-06-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtitle', models.CharField(max_length=100)),
                ('tech', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='NotesUpload')),
                ('comments', models.TextField()),
            ],
        ),
    ]
